AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  Max: 25

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 100

Naming/VariableName:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false
